allowBuilds:
  '@parcel/watcher': true
  postcss-combine-duplicated-selectors@https://codeload.github.com/poimen/postcss-combine-duplicated-selectors/tar.gz/bdf9223342b6b1da8a91d6727b6e4cf719f7def7: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@tailwindcss/cli@4.3.2'
  - '@tailwindcss/node@4.3.2'
  - '@tailwindcss/oxide-android-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-x64@4.3.2'
  - '@tailwindcss/oxide-freebsd-x64@4.3.2'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.2'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.2'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.2'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.2'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.2'
  - '@tailwindcss/oxide@4.3.2'
  - '@tailwindcss/postcss@4.3.2'
  - tailwindcss@4.3.2
