/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TwBasicComponent {
    }
    interface TwTransitionCards {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTwBasicComponentElement extends Components.TwBasicComponent, HTMLStencilElement {
    }
    var HTMLTwBasicComponentElement: {
        prototype: HTMLTwBasicComponentElement;
        new (): HTMLTwBasicComponentElement;
    };
    interface HTMLTwTransitionCardsElement extends Components.TwTransitionCards, HTMLStencilElement {
    }
    var HTMLTwTransitionCardsElement: {
        prototype: HTMLTwTransitionCardsElement;
        new (): HTMLTwTransitionCardsElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "tw-basic-component": HTMLTwBasicComponentElement;
        "tw-transition-cards": HTMLTwTransitionCardsElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TwBasicComponent {
    }
    interface TwTransitionCards {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "tw-basic-component": TwBasicComponent;
        "tw-transition-cards": TwTransitionCards;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "tw-basic-component": LocalJSX.TwBasicComponent & JSXBase.HTMLAttributes<HTMLTwBasicComponentElement>;
            "tw-transition-cards": LocalJSX.TwTransitionCards & JSXBase.HTMLAttributes<HTMLTwTransitionCardsElement>;
        }
    }
}
