/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoCard {
        "cardTitle": string;
        "subtitle": string;
    }
    interface DemoSection {
    }
    interface FooterNav {
    }
    interface HeroSection {
    }
    interface MainApp {
    }
    interface TopNavBar {
    }
}
declare global {
    interface HTMLDemoCardElement extends Components.DemoCard, HTMLStencilElement {
    }
    var HTMLDemoCardElement: {
        prototype: HTMLDemoCardElement;
        new (): HTMLDemoCardElement;
    };
    interface HTMLDemoSectionElement extends Components.DemoSection, HTMLStencilElement {
    }
    var HTMLDemoSectionElement: {
        prototype: HTMLDemoSectionElement;
        new (): HTMLDemoSectionElement;
    };
    interface HTMLFooterNavElement extends Components.FooterNav, HTMLStencilElement {
    }
    var HTMLFooterNavElement: {
        prototype: HTMLFooterNavElement;
        new (): HTMLFooterNavElement;
    };
    interface HTMLHeroSectionElement extends Components.HeroSection, HTMLStencilElement {
    }
    var HTMLHeroSectionElement: {
        prototype: HTMLHeroSectionElement;
        new (): HTMLHeroSectionElement;
    };
    interface HTMLMainAppElement extends Components.MainApp, HTMLStencilElement {
    }
    var HTMLMainAppElement: {
        prototype: HTMLMainAppElement;
        new (): HTMLMainAppElement;
    };
    interface HTMLTopNavBarElement extends Components.TopNavBar, HTMLStencilElement {
    }
    var HTMLTopNavBarElement: {
        prototype: HTMLTopNavBarElement;
        new (): HTMLTopNavBarElement;
    };
    interface HTMLElementTagNameMap {
        "demo-card": HTMLDemoCardElement;
        "demo-section": HTMLDemoSectionElement;
        "footer-nav": HTMLFooterNavElement;
        "hero-section": HTMLHeroSectionElement;
        "main-app": HTMLMainAppElement;
        "top-nav-bar": HTMLTopNavBarElement;
    }
}
declare namespace LocalJSX {
    interface DemoCard {
        "cardTitle"?: string;
        "subtitle"?: string;
    }
    interface DemoSection {
    }
    interface FooterNav {
    }
    interface HeroSection {
    }
    interface MainApp {
    }
    interface TopNavBar {
    }
    interface IntrinsicElements {
        "demo-card": DemoCard;
        "demo-section": DemoSection;
        "footer-nav": FooterNav;
        "hero-section": HeroSection;
        "main-app": MainApp;
        "top-nav-bar": TopNavBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-card": LocalJSX.DemoCard & JSXBase.HTMLAttributes<HTMLDemoCardElement>;
            "demo-section": LocalJSX.DemoSection & JSXBase.HTMLAttributes<HTMLDemoSectionElement>;
            "footer-nav": LocalJSX.FooterNav & JSXBase.HTMLAttributes<HTMLFooterNavElement>;
            "hero-section": LocalJSX.HeroSection & JSXBase.HTMLAttributes<HTMLHeroSectionElement>;
            "main-app": LocalJSX.MainApp & JSXBase.HTMLAttributes<HTMLMainAppElement>;
            "top-nav-bar": LocalJSX.TopNavBar & JSXBase.HTMLAttributes<HTMLTopNavBarElement>;
        }
    }
}
